version: '3'

services:
  proxy:
    build:
      context: "."
      dockerfile: ./Dockerfile
      target: builder
    command: ["/bin/sh", "-c", "mkfifo -m 666 /var/log/h2o_mruby.log; chmod nobody /var/log/h2o_mruby.log; h2o -c /app/.h2o/h2o.conf"]
    ports:
      - "8080:80"
      - "8888:8080"
    environment:
      TZ: Asia/Tokyo
      MELTING_POT_ENV: development

  backend_1:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates:ro
    ports:
     - "8090:80"
    environment:
     - NGINX_HOST=localhost
     - NGINX_PORT=80
     - "NGINX_TEXT={\\\"status\\\": \\\"pass\\\"}"

  redis_1:
    image: redis:6.2-rc2-alpine
    ports:
      - "6379:6379"

  redis_2:
    image: redis:6.2-rc2-alpine
    ports:
      - "6380:6379"
    command: ["/bin/sh", "-c", "redis-server --requirepass secret"]